#!/usr/bin/env python3
"""
Produce assets/examples/example-onboarding.md: a real transcript of `ledger.py init` driven by scripted answers.

The onboarding code runs unmodified; only three things are substituted so the transcript is reproducible and
contains no real machine, account or e-mail: the terminal check (forced interactive), the answers (a fixed list
that is echoed after each prompt), and host / account detection (a synthetic workstation plus a WSL distro,
and the fixture accounts). The scheduled task is NOT installed (schedule.install = n).

    python3 tests/make_onboarding_example.py
"""
import contextlib
import io
import json
import os
import shutil
import sys
import tempfile

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
sys.path.insert(0, os.path.join(ROOT, "scripts"))

ANSWERS = [
    "Northwind Trading Co.", "NORTHWIND TRADING CO.", "Ship it, measure it", "northwind.example · ops@northwind.example", "",
    "#1E3A8A", "Northwind Trading Co. · internal ledger", "system", "sqlite", "", "America/New_York", "y", "y", "y", "y", "y", "daily", "03:00", "mon", "n",
    "ops@build.northwind.example", "",  # one SSH host, then stop
]


def main():
    import detect_hosts
    import ledger
    tmp = tempfile.mkdtemp(prefix="ledger-onboarding-")
    os.environ["AI_USAGE_LEDGER_HOME"] = os.path.join(tmp, ".ai-usage-ledger")
    ledger.home_dir = lambda: os.environ["AI_USAGE_LEDGER_HOME"]
    answers = iter(ANSWERS)
    out = io.StringIO()

    def fake_input(prompt=""):
        a = next(answers)
        out.write(prompt + (a if a else "") + "\n")
        return a

    home = "/home/<you>"
    hosts = [
        {"name": "workstation", "kind": "local", "claude_roots": [home + "/.claude"], "codex_roots": [home + "/.codex"], "copilot_roots": [home + "/.copilot"],
         "opencode_dbs": [home + "/.local/share/opencode/opencode.db"], "cline_roots": ["cline=" + home + "/.config/Code/User/globalStorage/saoudrizwan.claude-dev"],
         "codex_sqlite": home + "/.codex/state_5.sqlite", "claude_stats_cache": home + "/.claude/stats-cache.json",
         "_found": ["Codex: %s/.codex" % home, "Claude Code: %s/.claude" % home, "Copilot CLI: %s/.copilot" % home, "opencode: %s/.local/share/opencode/opencode.db" % home, "cline: %s/.config/Code/User/globalStorage/saoudrizwan.claude-dev" % home]},
        {"name": "wsl-ubuntu", "kind": "wsl", "distro": "Ubuntu", "python": "python3", "share_fallback": "//wsl$/Ubuntu", "claude_roots": ["/home/<you>/.claude"], "codex_roots": ["/home/<you>/.codex"],
         "_found": ["Codex: //wsl$/Ubuntu/home/<you>/.codex", "Claude Code: //wsl$/Ubuntu/home/<you>/.claude"]},
    ]
    with open(os.path.join(ROOT, "examples", "accounts.fixtures.json"), encoding="utf-8") as fh:
        accounts = json.load(fh)
    detect_hosts.detect_hosts = lambda all_profiles=False, probe_wsl=True: (hosts, ["D:\\Users\\old-laptop is the same volume as an already detected profile (mapped drive or symlink); skipped"])
    detect_hosts.draft_accounts = lambda hs: accounts
    ledger.detect_hosts = detect_hosts

    import builtins
    real_input, real_isatty_in, real_isatty_out = builtins.input, sys.stdin.isatty, sys.stdout.isatty
    builtins.input = fake_input
    try:
        with contextlib.redirect_stdout(out):
            sys.stdin.isatty = lambda: True
            sys.stdout.isatty = lambda: True
            ns = type("A", (), {"yes": False, "reinit": False, "set": []})()
            ledger.onboard(ns)
    finally:
        builtins.input = real_input
        sys.stdin.isatty, sys.stdout.isatty = real_isatty_in, real_isatty_out
    def clean(txt):
        txt = txt.replace("\\\\", "/").replace("\\", "/")
        for real, alias in ((tmp, "~"), (ROOT, "<skill>")):
            txt = txt.replace(real.replace("\\", "/"), alias)
        return txt

    transcript = clean(out.getvalue())
    cfg = json.load(open(os.path.join(os.environ["AI_USAGE_LEDGER_HOME"], "config.json"), encoding="utf-8"))
    cfg_txt = clean(json.dumps({k: v for k, v in cfg.items() if k not in ("anonymize",)}, indent=2, ensure_ascii=False))
    md = """# Example: first-run onboarding

A transcript of `python3 scripts/ledger.py init` on a terminal. Press Enter to accept a default; every answer is
remembered in `~/.ai-usage-ledger/config.json` and mirrored into the store, so later `ledger.py run` calls never ask
again. From an agent or CI the same answers are passed as `--set key=value` with `--yes`.

The transcript below was generated by `tests/make_onboarding_example.py` from the real onboarding code with scripted
answers and a synthetic machine (a workstation, one WSL distro, the fixture accounts); no real host or account appears.

```text
$ python3 scripts/ledger.py init
%s```

The saved preferences (`~/.ai-usage-ledger/config.json`, salt omitted):

```json
%s
```

The same onboarding without prompts, as an agent would run it after asking the operator the questions in chat:

```bash
python3 scripts/ledger.py init --yes \\
  --set "brand.name=Northwind Trading Co." --set "brand.eyebrow=NORTHWIND TRADING CO." \\
  --set "brand.tagline=Ship it, measure it" --set "brand.contact=northwind.example · ops@northwind.example" \\
  --set brand.accent=#1E3A8A --set theme=system --set store.kind=sqlite --set timezone=America/New_York \\
  --set detect.all_profiles=y --set detect.wsl=y --set anonymize.on_every_run=y --set archive.raw_logs=y \\
  --set schedule.frequency=daily --set schedule.time=03:00 --set schedule.install=n
python3 scripts/ledger.py run
```

Pass `--set schedule.install=y` only after the operator has agreed to a Task Scheduler task or crontab entry being
created; `python3 scripts/ledger.py schedule install --dry-run` prints the exact command first.
""" % (transcript, cfg_txt)
    dst = os.path.join(ROOT, "assets", "examples", "example-onboarding.md")
    with open(dst, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(md)
    shutil.rmtree(tmp, ignore_errors=True)
    print("wrote", dst)


if __name__ == "__main__":
    main()
